// V169 mobile stability patch: remote skill VFX + nick/HP + chat + iPhone/Android
const V168_IOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
function v168Name(){try{return (getLocalProfile()?.name||'PLAYER').slice(0,16)}catch(_){return 'PLAYER'}}
function v168Send(obj){try{if(mpSocket&&mpSocket.readyState===WebSocket.OPEN)mpSocket.send(JSON.stringify(obj))}catch(_){}}
function v168LocalHp(){
  try{if(typeof playerHP==='number'&&Number.isFinite(playerHP))return playerHP}catch(_){ }
  try{if(typeof hp==='number'&&Number.isFinite(hp))return hp}catch(_){ }
  const txt=document.getElementById('hpText')?.textContent||document.querySelector('#hud .statNum')?.textContent||'';
  const n=parseFloat(txt); return Number.isFinite(n)?n:100;
}
function v168Hud(id){let el=document.querySelector(`.v168RemoteHud[data-id="${id}"]`);if(el)return el;el=document.createElement('div');el.className='v168RemoteHud';el.dataset.id=id;el.innerHTML='<div class="v168Name">PLAYER</div><div class="v168Hp"><div class="v168HpFill"></div></div><div class="v168HpText">100 / 100</div>';document.body.appendChild(el);return el}
function v168RemoveHud(id){document.querySelector(`.v168RemoteHud[data-id="${id}"]`)?.remove()}
function v168UpdateHud(id,rp){const el=document.querySelector(`.v168RemoteHud[data-id="${id}"]`);if(!el||!rp||!rp.visible){if(el)el.style.display='none';return}const p=rp.position.clone().add(new THREE.Vector3(0,3.6,0));p.project(camera);if(!(p.z>-1&&p.z<1&&Math.abs(p.x)<1.2&&Math.abs(p.y)<1.2)){el.style.display='none';return}el.style.display='block';el.style.left=((p.x*.5+.5)*innerWidth)+'px';el.style.top=((-p.y*.5+.5)*innerHeight)+'px'}
function v168Particle(pos,color,count=28,spread=2.2,life=850){const g=new THREE.Group();scene.add(g);for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.07,7,5),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.95,depthWrite:false}));m.position.copy(pos);m.userData.v=new THREE.Vector3((Math.random()-.5)*spread,(Math.random()-.2)*spread,(Math.random()-.5)*spread);g.add(m)}const born=performance.now();(function tick(){const t=(performance.now()-born)/life;if(t>=1){scene.remove(g);g.traverse(o=>{o.geometry?.dispose?.();o.material?.dispose?.()});return}for(const m of g.children){m.position.addScaledVector(m.userData.v,.024);m.userData.v.y-=.005;m.material.opacity=1-t}requestAnimationFrame(tick)})()}
function v168Orb(pos,color,r=.65,life=900){const m=new THREE.Mesh(new THREE.SphereGeometry(r,24,16),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.92,depthWrite:false}));m.position.copy(pos);scene.add(m);setTimeout(()=>{scene.remove(m);m.geometry.dispose();m.material.dispose()},life);return m}
function v168Ring(pos,color,r=1.3,life=900){const m=new THREE.Mesh(new THREE.RingGeometry(r*.72,r,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));m.position.copy(pos);m.rotation.x=Math.PI/2;scene.add(m);setTimeout(()=>{scene.remove(m);m.geometry.dispose();m.material.dispose()},life);return m}
function v168Pose(rp,skill){const p=rp?.userData?.parts;if(!p)return;if(skill==='blue'&&p.ra){p.ra.rotation.x=-1.35;p.ra.rotation.z=-.2}if(skill==='red'&&p.ra){p.ra.rotation.x=-1.05;p.ra.rotation.z=-.55}if(skill==='purple'){if(p.ra){p.ra.rotation.x=-1.3;p.ra.rotation.z=-.75}if(p.la){p.la.rotation.x=-1.3;p.la.rotation.z=.75}}if(skill==='domain'||skill==='miniVoid'){if(p.ra){p.ra.rotation.x=-1.85;p.ra.rotation.z=-.35}if(p.la){p.la.rotation.x=-1.85;p.la.rotation.z=.35}}}
function v168Skill(id,skill,msg={}){if(id===mpMyId)return;const rp=getRemotePlayer(id);v168Pose(rp,skill);if(Number.isFinite(+msg.x)){rp.position.set(+msg.x||0,+msg.y||0,+msg.z||0);rp.userData.netTarget.copy(rp.position)}const yaw=Number.isFinite(+msg.yaw)?+msg.yaw:(rp.userData.netYaw||rp.rotation.y||0);const f=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)).normalize();const base=rp.position.clone().add(new THREE.Vector3(0,1.7,0));let pos=base.clone().add(f.multiplyScalar(1.7)),color=0x3da0ff;if(skill==='red')color=0xff3150;if(skill==='purple'||skill==='selfPurple')color=0xa74cff;if(skill==='blueOverhead')pos=rp.position.clone().add(new THREE.Vector3(0,4.3,0));if(skill==='domain'||skill==='miniVoid'){pos=rp.position.clone().add(new THREE.Vector3(0,2.2,0));v168Orb(pos,skill==='domain'?0x5060ff:0x22dfff,4.5,1500);v168Ring(rp.position.clone().add(new THREE.Vector3(0,.08,0)),0x63c7ff,5.8,1500);v168Particle(pos,0x7fd7ff,70,6,1500);return}v168Orb(pos,color,skill==='purple'||skill==='selfPurple'?1.05:.68,1100);v168Ring(pos,color,skill==='purple'||skill==='selfPurple'?1.8:1.2,950);v168Particle(pos,color,skill==='purple'||skill==='selfPurple'?55:34,skill==='purple'?3.5:2.4,1100)}

// Reuse the existing chat panel when present; only create one if the base game has none.
let v168Chat=document.getElementById('chatPanel');
if(!v168Chat){v168Chat=document.createElement('div');v168Chat.id='v168Chat';v168Chat.innerHTML='<div id="v168ChatLog"></div><div class="v168ChatRow"><input id="v168ChatInput" maxlength="120" placeholder="채팅 입력"><button id="v168ChatSend">전송</button></div>';document.body.appendChild(v168Chat)}
const v168Log=document.getElementById('chatLog')||document.getElementById('v168ChatLog');
const v168Input=document.getElementById('chatInput')||document.getElementById('v168ChatInput');
const v168SendBtn=document.getElementById('chatSend')||document.getElementById('v168ChatSend');
function v168AddChat(name,text){if(!v168Log)return;const d=document.createElement('div');d.className='v168ChatLine';const n=document.createElement('b');n.textContent=(name||'PLAYER')+': ';const t=document.createElement('span');t.textContent=String(text||'');d.append(n,t);v168Log.appendChild(d);while(v168Log.children.length>40)v168Log.removeChild(v168Log.firstChild);v168Log.scrollTop=v168Log.scrollHeight}
function v168SendChat(){if(!v168Input)return;const text=(v168Input.value||'').trim();if(!text)return;v168Send({type:'chat',name:v168Name(),text:text.slice(0,120)});v168AddChat(v168Name(),text.slice(0,120));v168Input.value=''}
if(v168SendBtn&&!v168SendBtn.dataset.v168Bound){v168SendBtn.dataset.v168Bound='1';v168SendBtn.addEventListener('click',v168SendChat)}
if(v168Input&&!v168Input.dataset.v168Bound){v168Input.dataset.v168Bound='1';v168Input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();v168SendChat()}})}

let v168BoundSocket=null;setInterval(()=>{try{if(mpSocket&&mpSocket!==v168BoundSocket){v168BoundSocket=mpSocket;mpSocket.addEventListener('message',e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='presence'){const rp=getRemotePlayer(m.id),h=v168Hud(m.id),max=Math.max(1,+m.maxHp||100),hp2=Math.max(0,Math.min(max,+m.hp||max));h.querySelector('.v168Name').textContent=String(m.name||'PLAYER').slice(0,16);h.querySelector('.v168HpFill').style.width=(hp2/max*100)+'%';h.querySelector('.v168HpText').textContent=Math.round(hp2)+' / '+Math.round(max)}else if(m.type==='skill')v168Skill(m.id,m.skill,m);else if(m.type==='chat')v168AddChat(m.name,m.text);else if(m.type==='left')v168RemoveHud(m.id)})}}catch(_){ }},300);
setInterval(()=>{try{if(!started)return;v168Send({type:'presence',name:v168Name(),hp:Math.max(0,Math.round(v168LocalHp())),maxHp:100});for(const [id,rp] of remotePlayers)v168UpdateHud(id,rp)}catch(_){ }},180);
function v168SkillSend(skill){try{if(!started)return;v168Send({type:'skill',skill,x:+player.position.x.toFixed(3),y:+player.position.y.toFixed(3),z:+player.position.z.toFixed(3),yaw:+player.rotation.y.toFixed(4)})}catch(_){}}
document.addEventListener('keydown',e=>{if(e.repeat||e.target===v168Input)return;const k=e.key.toLowerCase();if(k==='z')v168SkillSend('blue');else if(k==='x')v168SkillSend('red');else if(k==='c')v168SkillSend('purple');else if(k==='v')v168SkillSend('domain')},true);
[['mbZ','blue'],['mbX','red'],['mbC','purple'],['mbV','domain']].forEach(([id,s])=>{const b=document.getElementById(id);if(b&&!b.dataset.v168Skill){b.dataset.v168Skill='1';b.addEventListener('pointerdown',()=>v168SkillSend(s),true)}});

function v168Resize(){try{const vv=window.visualViewport;const w=Math.max(1,Math.round(vv?.width||window.innerWidth));const h=Math.max(1,Math.round(vv?.height||window.innerHeight));renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,V168_IOS?1.35:1.6));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}catch(_){}}
window.addEventListener('resize',v168Resize,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(v168Resize,300),{passive:true});window.visualViewport?.addEventListener('resize',v168Resize,{passive:true});setTimeout(v168Resize,80);
